apiVersion: v1
kind: ConfigMap
metadata:
  name: app-prop-config
data:
{{- range $line := .Files.Lines "application.properties" }}
  {{/* Break the line into words */}}
  {{- $kv := splitList "=" $line -}}
  {{- $k := first $kv -}}
  {{- if $k }}
    {{ $k |upper|replace "." "_"}}: {{ last $kv | quote }}
  {{- end }}

{{- end }}